name: epicquests
description: "Epic Quests - 2D RPG Productivity Game"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  go_router: ^17.1.0
  shared_preferences: ^2.5.4
  intl: ^0.19.0
  provider: ^6.1.2
  video_player: ^2.9.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.0
  uuid: ^4.5.1
  audioplayers: ^6.1.0
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  flame: ^1.24.0
  vibration: ^2.0.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/door/
    - assets/images/avatar/
    - assets/icons/
    - assets/video/
    # - assets/audio/sfx/
    # - assets/audio/music/
    # - assets/sprites/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
